import chromadb
from sentence_transformers import SentenceTransformer

# --- STEP 1: DATA INGESTION ---
# Load the raw transcript generated by ingest.py
with open("transcript.txt", "r", encoding="utf-8") as f:
    text = f.read()

# --- STEP 2: CHUNKING LOGIC ---
# We use a sliding window approach to preserve context between chunks.
window_size = 3  # Lines per chunk
overlap = 1       # Lines to repeat from previous chunk to ensure no context is lost

lines = [l.strip() for l in text.split('\n') if len(l.strip()) > 1]
chunks = []

# Iterate through lines creating overlapping segments
for i in range(0, len(lines), window_size - overlap):
    chunk = " ".join(lines[i : i + window_size])
    if len(chunk) > 10: # Ignore fragments that are too short to be useful
        chunks.append(chunk)

# --- STEP 3: EMBEDDING MODEL INITIALIZATION ---
# 'all-MiniLM-L6-v2' is a fast, efficient model for converting text to math vectors
model = SentenceTransformer('all-MiniLM-L6-v2')

# --- STEP 4: DATABASE SETUP ---
# Initialize ChromaDB as a persistent local database
db_client = chromadb.PersistentClient(path="./my_ai_memory")

# Fresh Start: Delete existing collection to avoid mixing data from different videos
try:
    db_client.delete_collection(name="rick_memory")
except Exception:
    pass # Ignore error if collection doesn't exist

collection = db_client.get_or_create_collection(name="rick_memory")

# --- STEP 5: VECTORIZATION & STORAGE ---
print("--- LOADING MEMORY ---")
for i, chunk in enumerate(chunks):
    # Convert text chunk into a 384-dimensional numerical vector
    vector = model.encode(chunk).tolist()
    
    # Store the vector, the text, and a unique ID in the database
    collection.add(
        ids=[f"id_{i}"],
        embeddings=[vector],
        documents=[chunk]
    )
print(f" SUCCESS: {len(chunks)} memories stored! ")

# --- STEP 6: TEST INTERFACE ---
print("\n--- AI MEMORY READY ---")
while True:
    question = input("\nAsk a question (or type 'exit'): ")
    if question.lower() == 'exit': break

    # Perform a similarity search in the Vector DB
    results = collection.query(
        query_texts=[question],
        n_results=3
    )

    print("\nClosest matches found in memory:")
    for doc in results['documents'][0]:
        print(f"-> {doc}")